# Calculates the page rank for each url using the graph generated by web crawler
def compute_ranks(graph):
    d = 0.85
    num_loops = 10
    page_ranks = {}
    npages = len(graph)

    for page in graph:
        page_ranks[page] = 1.0 / npages

    for i in range(0, num_loops):
        new_ranks = {}
        for page in graph:
            new_rank = (1 - d) / npages
            for node in graph:
                if page in graph[node]:
                    new_rank = new_rank + d * (page_ranks[node] / len(graph[node]))
            new_ranks[page] = new_rank
        page_ranks = new_ranks

    ranks = page_ranks
    return ranks
